var layer_names = {
  tidal_islands: { n: "tidal island [s]", e: "🏝️" },
  inland_islands: { n: "inland island [s]", e: "🏝️" },
  coral_islands: { n: "coral island [s]", e: "🏝️" },
  desert_islands: { n: "desert island [s]", e: "🏝️" },
  high_islands: { n: "high island [s]", e: "🏝️" },
  other_islands: { n: "island[other islands]", e: "🏝️" },
  hot_springs: { n: "hot spring [s]", e: "💧" },
  geysers: { n: "geyser [s]", e: "💧" },
  springs_others: { n: "spring[other springs]", e: "💧" },
  mountain_peaks: { n: "mountain peak [s]", e: "⛰️" },
  volcanoes: { n: "volcano  [es]", e: "⛰️" },
  caves: { n: "cave [s]", e: "⛰️" },
  canyons: { n: "canyon [s]", e: "⛰️" },
  rock_formations: { n: "rock formation [s]", e: "⛰️" },
  crater_lakes: { n: "crater lake [s]", e: "🌊" },
  rift_lakes: { n: "rift lake [s]", e: "🌊" },
  salt_lakes: { n: "salt lake [s]", e: "🌊" },
  dry_lakes: { n: "dry lake [s]", e: "🌊" },
  reservoirs: { n: "reservoir [s]", e: "🌊" },
  rivers: { n: "river [s]", e: "🌊" },
  canals: { n: "canal [s]", e: "🌊" },
  waterfalls: { n: "waterfall [s]", e: "🌊" },
  lagoons: { n: "lagoon [s]", e: "🌊" },
  other_lakes: { n: "lake[other lakes]", e: "🌊" },
  golden_sand_beaches: { n: "golden sand beach  [es]", e: "🏖️" },
  white_sand_beaches: { n: "white sand beach  [es]", e: "🏖️" },
  black_sand_beaches: { n: "black sand beach  [es]", e: "🏖️" },
  shingle_beaches: { n: "shingle beach  [es]", e: "🏖️" },
  rocks_beaches: { n: "rocks beach  [es]", e: "🏖️" },
  urbans_beaches: { n: "urbans beach  [es]", e: "🏖️" },
  nude_beaches: { n: "nude beach  [es]", e: "🏖️" },
  other_beaches: { n: "beach[other beaches]", e: "🏖️" },
  aquatic_protected_areas: { n: "aquatic protected area [s]", e: "🏞️" },
  wildlife_reserves: { n: "wildlife reserve [s]", e: "🏞️" },
  national_parks: { n: "national park [s]", e: "🏞️" },
  nature_reserves_others: {
    n: "nature reserve[other nature reserves]",
    e: "🏞️"
  },
  natural_monuments: { n: "natural monument [s]", e: "🏞️" },
  other_nature_conservation_areas: {
    n: "nature conservation area [s]",
    e: "🏞️"
  },
  glaciers: { n: "Glacier [s]", e: "🏔️" },
  national_museums: { n: "national museum [s]", e: "🏛️" },
  local_museums: { n: "local museum [s]", e: "🏛️" },
  maritime_museums: { n: "maritime museum [s]", e: "🏛️" },
  railway_museums: { n: "railway museum [s]", e: "🏛️" },
  aviation_museums: { n: "aviation museum [s]", e: "🏛️" },
  automobile_museums: { n: "automobile museum [s]", e: "🏛️" },
  computer_museums: { n: "computer museum [s]", e: "🏛️" },
  heritage_railways: { n: "heritage railway [s]", e: "🏛️" },
  other_technology_museums: {
    n: "technology museum[other technology museums]",
    e: "🏛️"
  },
  science_museums: { n: "science museum [s]", e: "🏛️" },
  planetariums: { n: "planetarium [s]", e: "🏛️" },
  military_museums: { n: "military museum [s]", e: "🏛️" },
  history_museums: { n: "history museum [s]", e: "🏛️" },
  archaeological_museums: { n: "archaeological museum [s]", e: "🏛️" },
  biographical_museums: { n: "biographical museum [s]", e: "🏛️" },
  open_air_museums: { n: "open-air museum [s]", e: "🏛️" },
  fashion_museums: { n: "fashion museum [s]", e: "🏛️" },
  children_museums: { n: "children museum [s]", e: "🏛️" },
  historic_house_museums: { n: "historic house museum [s]", e: "🏛️" },
  art_galleries: { n: "art gallery  [ies]", e: "🏛️" },
  zoos: { n: "zoo [s]", e: "🏛️" },
  aquariums: { n: "aquarium [s]", e: "🏛️" },
  other_museums: { n: "museum[other museums]", e: "🏛️" },
  sylvan_theatres: { n: "sylvan theatre [s]", e: "🎭" },
  opera_houses: { n: "opera house [s]", e: "🎭" },
  music_venues: { n: "music venue [s]", e: "🎭" },
  concert_halls: { n: "concert hall [s]", e: "🎭" },
  puppetries: { n: "puppetry  [ies]", e: "🎭" },
  children_theatres: { n: "сhildren\u0027s theatre [s]", e: "🎭" },
  other_theatres: { n: "theatre[other theatres]", e: "🎭" },
  cinemas: { n: "movie theatre [s]", e: "🎭" },
  circuses: { n: "circus  [es]", e: "🎭" },
  wall_painting: { n: "wall painting", e: "⛲" },
  squares: { n: "street[squares and streets]", e: "⛲" },
  installation: { n: "installation", e: "⛲" },
  gardens_and_parks: { n: "park[gardens and parks]", e: "⛲" },
  fountains: { n: "fountain [s]", e: "⛲" },
  sculptures: { n: "sculpture [s]", e: "⛲" },
  historic_districts: { n: "historic district [s]", e: "🛡️" },
  historic_settlements: { n: "historic settlement [s]", e: "🛡️" },
  fishing_villages: { n: "fishing village [s]", e: "🛡️" },
  battlefields: { n: "battlefield [s]", e: "🛡️" },
  castles: { n: "castle [s]", e: "🏰" },
  hillforts: { n: "hillfort [s]", e: "🏰" },
  fortified_towers: { n: "fortified tower [s]", e: "🏰" },
  defensive_walls: { n: "defensive wall [s]", e: "🏰" },
  bunkers: { n: "bunker [s]", e: "🏰" },
  kremlins: { n: "kremlin [s]", e: "🏰" },
  other_fortifications: { n: "fortification[other fortifications]", e: "🏰" },
  milestones: { n: "milestone [s]", e: "🗿" },
  monuments: { n: "monument [s]", e: "🗿" },
  megaliths: { n: "megalith [s]", e: "🏺" },
  menhirs: { n: "menhir [s]", e: "🏺" },
  roman_villas: { n: "roman villa [s]", e: "🏺" },
  cave_paintings: { n: "cave painting [s]", e: "🏺" },
  settlements: { n: "settlement [s]", e: "🏺" },
  rune_stones: { n: "rune stone [s]", e: "🏺" },
  other_archaeological_sites: { n: "archaeological site [s]", e: "🏺" },
  cemeteries: { n: "cemetery  [ies]", e: "⚱️" },
  war_graves: { n: "war grave [s]", e: "⚱️" },
  necropolises: { n: "necropolis  [es]", e: "⚱️" },
  dolmens: { n: "dolmen [s]", e: "⚱️" },
  tumuluses: { n: "tumulus  [es]", e: "⚱️" },
  mausoleums: { n: "mausoleum [s]", e: "⚱️" },
  war_memorials: { n: "war memorial [s]", e: "⚱️" },
  crypts: { n: "crypt [s]", e: "⚱️" },
  other_burial_places: { n: "burial place[other burial places]", e: "⚱️" },
  eastern_orthodox_churches: { n: "eastern orthodox church  [es]", e: "⛪" },
  catholic_churches: { n: "catholic church  [es]", e: "⛪" },
  other_churches: { n: "church[other churches]", e: "⛪" },
  cathedrals: { n: "cathedral [s]", e: "🛐" },
  mosques: { n: "mosque [s]", e: "🕌" },
  synagogues: { n: "synagogue [s]", e: "🕍" },
  buddhist_temples: { n: "buddhist temple [s]", e: "☸️" },
  hindu_temples: { n: "hindu temple [s]", e: "🕉️" },
  egyptian_temples: { n: "egyptian temple [s]", e: "🛐" },
  other_temples: { n: "temple[other temples]", e: "🛐" },
  monasteries: { n: "monastery  [ies]", e: "🛐" },
  pyramids: { n: "pyramid [s]", e: "🏡" },
  amphitheatres: { n: "amphitheatre [s]", e: "🏡" },
  triumphal_archs: { n: "triumphal arch [s]", e: "🏡" },
  palaces: { n: "palace [s]", e: "🏡" },
  manor_houses: { n: "manor house [s]", e: "🏡" },
  wineries: { n: "wineries", e: "🏡" },
  farms: { n: "farms", e: "🏡" },
  other_buildings_and_structures: {
    n: "structure[buildings and structures]",
    e: "🏡"
  },
  destroyed_objects: { n: "destroyed object [s]", e: "🏡" },
  skyscrapers: { n: "Skyscraper [s]", e: "🏙️" },
  moveable_bridges: { n: "moveable bridge [s]", e: "🌉" },
  stone_bridges: { n: "stone bridge [s]", e: "🌉" },
  viaducts: { n: "viaduct [s]", e: "🌉" },
  roman_bridges: { n: "Roman bridge [s]", e: "🌉" },
  footbridges: { n: "footbridge [s]", e: "🌉" },
  aqueducts: { n: "aqueduct [s]", e: "🌉" },
  suspension_bridges: { n: "suspension bridge [s]", e: "🌉" },
  other_bridges: { n: "bridge[other bridges]", e: "🌉" },
  observation_towers: { n: "observation tower [s]", e: "🗼" },
  watchtowers: { n: "watchtower [s]", e: "🗼" },
  water_towers: { n: "water tower [s]", e: "🗼" },
  transmitter_towers: { n: "transmitter tower [s]", e: "🗼" },
  clock_towers: { n: "clock tower [s]", e: "🗼" },
  bell_towers: { n: "bell tower [s]", e: "🗼" },
  minarets: { n: "minaret [s]", e: "🗼" },
  other_towers: { n: "tower[other towers]", e: "🗼" },
  lighthouses: { n: "Lighthouse [s]", e: "🗼" },
  railway_stations: { n: "Railway station [s]", e: "🏭" },
  factories: { n: "Factory  [ies]", e: "🏭" },
  mints: { n: "Mint [s]", e: "🏭" },
  power_stations: { n: "Power station [s]", e: "🏭" },
  dams: { n: "Dam [s]", e: "🏭" },
  mills: { n: "Mill [s]", e: "🏭" },
  abandoned_railway_stations: { n: "Abandoned railway station [s]", e: "🏭" },
  abandoned_mineshafts: { n: "Abandoned mineshaft [s]", e: "🏭" },
  mineshafts: { n: "Mineshaft [s]", e: "🏭" },
  other_buildings: { n: "Building[Other buildings]", e: "🏭" },
  sundials: { n: "Sundial [s]", e: "📸" },
  view_points: { n: "View point [s]", e: "📸" },
  red_telephone_boxes: { n: "Red telephone box  [es]", e: "📸" },
  tourist_object: { n: "tourist attraction [s]", e: "📸" },
  historic_object: { n: "historic attraction [s]", e: "📸" },
  amusement_parks: { n: "amusement park [s]", e: "📸" },
  miniature_parks: { n: "miniature park [s]", e: "📸" },
  water_parks: { n: "water park [s]", e: "📸" },
  roller_coasters: { n: "roller coaster [s]", e: "📸" },
  ferris_wheels: { n: "ferris wheel [s]", e: "📸" },
  other_amusement_rides: {
    n: "amusement ride[other amusement rides]",
    e: "📸"
  },
  saunas: { n: "sauna[s]", e: "📸" },
  thermal_baths: { n: "thermal bath [s]", e: "📸" },
  open_air_baths: { n: "open-air bath [s]", e: "📸" },
  other_bathhouses: { n: "bathhouse [s]", e: "📸" },
  skiing: { n: "skiing", e: "📸" },
  cross_country_skiing: { n: "cross country skiing", e: "📸" },
  other_winter_sports: { n: "winter sport[other winter sports]", e: "📸" },
  dive_centers: { n: "dive center [s]", e: "📸" },
  dive_spots: { n: "dive spot [s]", e: "📸" },
  wrecks: { n: "wreck [s]", e: "📸" },
  climbing: { n: "climbing", e: "📸" },
  surfing: { n: "surfing", e: "📸" },
  kitesurfing: { n: "kitesurfing", e: "📸" },
  stadiums: { n: "stadium [s]", e: "📸" },
  pools: { n: "pool [s]", e: "📸" },
  strip_clubs: { n: "strip club [s]", e: "📸" },
  casino: { n: "casino", e: "📸" },
  brothels: { n: "brothel [s]", e: "📸" },
  nightclubs: { n: "nightclub [s]", e: "📸" },
  alcohol: { n: "alcohol", e: "📸" },
  adult_hotels: { n: "love hotel [s]", e: "📸" },
  erotic_shops: { n: "erotic shop [s]", e: "📸" },
  hookah: { n: "hookah", e: "📸" },
  car_rental: { n: "Car rental", e: "📸" },
  car_sharing: { n: "Car sharing", e: "📸" },
  car_wash: { n: "Car wash", e: "📸" },
  charging_station: { n: "Charging station [s]", e: "📸" },
  bicycle_rental: { n: "Bicycle rental", e: "📸" },
  boat_sharing: { n: "Boat sharing", e: "📸" },
  fuel: { n: "Fuel", e: "📸" },
  supermarkets: { n: "Supermarket [s]", e: "📸" },
  conveniences: { n: "Convenience [s]", e: "📸" },
  fish_stores: { n: "Fish store [s]", e: "📸" },
  outdoor: { n: "Outdoor", e: "📸" },
  malls: { n: "Mall [s]", e: "📸" },
  marketplaces: { n: "Marketplace [s]", e: "📸" },
  bakeries: { n: "Bakery  [ies]", e: "📸" },
  restaurants: { n: "Restaurant [s]", e: "📸" },
  cafes: { n: "Cafe [s]", e: "📸" },
  fast_food: { n: "Fast food", e: "📸" },
  food_courts: { n: "Food court [s]", e: "📸" },
  pubs: { n: "Pub [s]", e: "📸" },
  bars: { n: "Bar [s]", e: "📸" },
  biergartens: { n: "Biergarten [s]", e: "📸" },
  picnic_site: { n: "Picnic site [s]", e: "📸" },
  bank: { n: "Bank [s]", e: "📸" },
  atm: { n: "ATM", e: "📸" },
  bureau_de_change: { n: "Bureau de change", e: "📸" },
  apartments: { n: "Apartment [s]", e: "📸" },
  guest_houses: { n: "Guest house [s]", e: "📸" },
  campsites: { n: "Campsite [s]", e: "📸" },
  resorts: { n: "Resort [s]", e: "📸" },
  motels: { n: "Motel [s]", e: "📸" },
  other_hotels: { n: "Hotel [s]", e: "📸" },
  hostels: { n: "Hostel [s]", e: "📸" },
  villas_and_chalet: { n: "Villa [Villas and chalet]", e: "📸" },
  alpine_hut: { n: "Alpine hut [s]", e: "📸" },
  love_hotels: { n: "Love hotel [s]", e: "📸" }
};

var isoCountries = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AN: "Netherlands Antilles",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Bonaire, Saint Eustatius, and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos [Keeling] Islands",
  CD: "Belgian Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Ivory Coast",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CS: "Serbia and Montenegro",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "The Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Hashemite Kingdom of Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "St Kitts and Nevis",
  KP: "North Korea",
  KR: "Republic of Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "St Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Republic of Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Republic of Moldova",
  ME: "Montenegro",
  MF: "Saint Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "Macedonia",
  ML: "Mali",
  MM: "Myanmar [Burma]",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Republic of Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "Republic of South Sudan",
  ST: "São Tomé and Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Swaziland",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "East Timor",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "U.S. Minor Outlying Islands",
  US: "United States of America",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "St Vincent and Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  XK: "Republic of Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "Republic of South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe"
};

export function getCountryName(countryCode) {
  if (isoCountries.hasOwnProperty(countryCode)) {
    return isoCountries[countryCode];
  } else {
    return countryCode;
  }
}

function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

function parsePlural(label) {
  var sb_single = new Array("");
  var sb_plural = new Array("");
  var spaces = 0;
  for (var i = 0; i < label.length; i++) {
    var ch = label.charAt(i);
    if (ch !== "[") {
      sb_single.push(ch);
      sb_plural.push(ch);
      if (ch === " ") {
        spaces++;
      } else {
        spaces = 0;
      }
    } else {
      var sb = new Array("");
      var j = i + 1;
      for (; j < label.length; j++) {
        ch = label.charAt(j);
        if (ch === "]") break;
        sb.push(ch);
      }
      var len = j - i - 1;
      i = sb_plural.length;
      sb_plural.splice(Math.max(0, i - len), len);
      sb_plural.push(sb.join(""));
      if (spaces !== 0) {
        i = sb_single.length;
        sb_single.splice(Math.max(0, i - spaces), spaces);
      }
      i = j;
    }
  }
  return {
    single: capitalizeFirstLetter(sb_single.join("")),
    plural: sb_plural.join("")
  };
}

export function getCategoryName(kinds) {
  let names = [];
  kinds.split(",").forEach(function(kind) {
    let item = layer_names[kind];
    if (item) names.push(parsePlural(item.n).single);
  });
  return names.join(", ");
}
